env:
  global:
    - secure: bxJvnH0G/A+p5aOkX56h8cO3LXwBzbbZCJnaCzXQLEkvAIhNasaafzqsIEC+26IXuXlLtEhjxOqLIMoXOcgrJKUFRbpR+EkVPAjuXsei3nJ6eHReOfRfYsOAqSPgVjcF+m0XAUDKjaA79fxDXNvSSvOWlRbch++N1YT4lJCaSRA= 
language: rust
script:
  - cargo build --verbose
  - cargo test --verbose
  - cargo doc --verbose --no-deps
after_script:
  - mv target/doc . 
  - curl http://www.rust-ci.org/artifacts/put?t=$RUSTCI_TOKEN | sh
