[package]
name = "entity_system"
version = "0.0.1"
authors = ["Lori Holden <email@loriholden.com>"]

[lib]
name = "entity_system"
doctest = false

[dependencies.uuid]
git = "https://github.com/rust-lang/uuid.git"
